services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app  # Mounts backend folder for live updates
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - ./backend/.env

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend:/app  # Mount the frontend folder to allow for live updates
